### ISSUE TITLE
A roadmap towards improving tests and CI

### ISSUE THREAD

**Issue by utensil** [pygae/galgebra#3]
- [x] Move tests to a seperate folder, like `test` in https://github.com/pygae/clifford
- [x] Setup test coverage in CI: pygae/galgebra#8
- [x] Add and pass pylint in CI
- [x] Provide readable docs for tests with LaTeX formulas
- [x] Verify tests under examples and convert some important ones of them to tests
- [x] Organize tests in themes
- [x] Further verify Python 3 compatibility in tests, see also https://docs.python.org/3/howto/pyporting.html

Comments welcome :smiley:

**Comment by hugohadfield** [comment]
I am very keen on this and am looking forward to getting stuck into writing tests, very busy for the next few week with my first year phd viva but after that I will be much more free to help :)

**Comment by utensil** [comment]
Mission accomplished, silently.
