### ISSUE TITLE
Fix and close lingering issues in brombo/galgebra

### ISSUE THREAD

**Issue by utensil** [pygae/galgebra#4]
- [x] Python 3 support: brombo/galgebra#37 (#119), brombo/galgebra#35 (#117), , brombo/galgebra#33 (lost to time)
- [x] non-root installation: brombo/galgebra#36 (#118)
- [x] pip installation: brombo/galgebra#39 (#119)
- [x] self import: brombo/galgebra#27 (lost to time)
- [x] no .pyc: brombo/galgebra#2 (fixed)
- [ ] properties: brombo/galgebra#23 (#132)
- [x] my own (review and close, most likely merged by #2): brombo/galgebra#19 (#119), brombo/galgebra#20 (#110)
- [ ] Visualization: brombo/galgebra#4 (#125)
- [ ] N-dim arrays: brombo/galgebra#3 (#102)

Misc bugs that need some time to fix:

  - [ ] brombo/galgebra#38 (#127)
  - [ ] brombo/galgebra#34 (#126)
  - [ ] brombo/galgebra#32 (#116) ( @arsenovic 's )
  - [ ] brombo/galgebra#31 (#115) (quite some discussion) 
  - [ ] brombo/galgebra#29 (#114, @arsenovic 's )
  - [ ] brombo/galgebra#28 (#113, @arsenovic 's )
  - [ ] brombo/galgebra#18 (#108)
  - [ ] brombo/galgebra#10 (#105)
  - [ ] brombo/galgebra#9 (#104) (seems fixed)
  - [ ] brombo/galgebra#1 (#101) (seems fixed)

**Comment by utensil** [comment]
Attempting to manage them and the new issues in https://github.com/pygae/galgebra/projects/1

**Comment by eric-wieser** [comment]
@utensil, can we close this in favor of the separate issues that now exist for each?

**Comment by utensil** [comment]
Of course.

**Comment by utensil** [comment]
The issues listed here are all fixed but #115 . 🎉
