### ISSUE TITLE
A roadmap towards improving documentation

### ISSUE THREAD

**Issue by utensil** [pygae/galgebra#5]
- [x] Update installation instructions
- [x] Add brief overview and quickstart in README.md
- [x] Setup readthedoc with nbsphinx (see https://github.com/brombo/galgebra/pull/15#issuecomment-422364951 and #9 )
- [x] Convert existing LaTeX docs
- [x] Convert existing class docs
- [ ] Improve existing class docs
- <del>[ ] add some doctests?</del>

Comments welcome.

**Comment by hugohadfield** [comment]
Looks great :)

**Comment by utensil** [comment]
Closing as #9 is now merged and future work has been documented in it.

**Comment by waldyrious** [comment]
> Closing as #9 is now merged and future work has been documented in it.

I'd rather move the checklist of future tasks to this issue and reopen it (or have it in a new issue if you prefer). I think it makes more sense to have an _open_ issue tracking work to be done, than task lists semi-buried in closed issues.

**Comment by utensil** [comment]
I closed this because the descriptions of the tasks to be done is less specific than #9 and there's too many issues open.

But what you suggested makes sense, I'll keep it open until I have a better open issue/PR to put the task list.

**Comment by waldyrious** [comment]
> the descriptions of the tasks to be done is less specific than #9 

I don't think that has to be a permanent state of affairs. The title of this issue is "A roadmap towards improving documentation", so it would make sense to me to add a new comment with the updated checklist of upcoming tasks, copied from #9 (especially since the chekclist goes beyond the scope of #9 anyway). But again, a new issue would work just as well. The important think is to have an open issue with the list of tasks to be done to improve documentation.

By the way, we might want to consider applying for [Season of Docs](https://opensource.googleblog.com/2019/03/introducing-season-of-docs.html) for this work :)

**Comment by utensil** [comment]
> it would make sense to me to add a new comment with the updated checklist of upcoming tasks, copied from #9

I intend to use one or more different issues/PRs or milestone/project or something else. It's not just copy-pasting from #9, I need to reorganize the tasks or regroup them based on my current work on fixing examples. The task listed in this issue was very vague and can only serve as historical obsolete description and now kept open to be a placeholder.



> The important think is to have an open issue with the list of tasks to be done to improve documentation.

I don't think there should be such one open issue for the long run, it's costly to maintain such an issue and keep it up-to-date. Instead I would imagine a series of issues labeled `documentation` and possibly `help wanted` for users and potential contributors to understand what's being improved about documentation.

**Comment by utensil** [comment]
> By the way, we might want to consider applying for [Season of Docs](https://opensource.googleblog.com/2019/03/introducing-season-of-docs.html) for this work :)

IMHO, we are not there yet. Documentation isn't everything. There're many aspects in galgebra are in need of efforts to improve, since now it has a reasonable doc set up, I would personally focus on other aspects and gradually improve the docs along the way when it makes sense. Also we don't have much feedback on the new doc and there're still many valuable information (but outdated here and there) scattered in different sources. There were attempts to maintain a sphinx doc for galgebra when it was part of sympy and its maintenance was dropped by brombo and replaced with the TeX version. By turning it into nbsphinx I've potentially made it less maintainable and recreated a new fragment of the whole picture.

**Comment by utensil** [comment]
Primary goals accomplished and improving existing class docs is a continuous practice and being worked on in the spirit of #300 .
